"""empty message

Revision ID: 9a533c64197a
Revises: 24fb24357b38
Create Date: 2019-11-26 15:11:41.563046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a533c64197a'
down_revision = '24fb24357b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'time')
    # ### end Alembic commands ###
